### ISSUE TITLE
How to prepare own dataset

### ISSUE THREAD

**Issue by ericosmic** [mil-tokyo/neural_melody#2]
The result of this model sound better than other music generate model. I want to train it by myself data,  but I don't know how to prepare the training data. Could you give some introduction.

**Comment by TE-andrewshin** [comment]
(We've discussed this over e-mail but let me copy and paste it here for other people)

First, you will have to manually annotate your own data.
Following is the description on how to annotate and convert your data.

data.mat basically contains two-hot vectors.
Each 59-dimension vector represents a two-bar progress within a song.
So, for example, if your song contains 100 bars, you will have 50 vectors of 59-dimension.
First 55 dimension corresponds to chord-progression of the two-bar progression, ordered as following:
['C;Em', 'A#;F', 'Dm;Em', 'Dm;G', 'Dm;C', 'Am;Em', 'F;C', 'F;G', 'Dm;F', 'C;C', 'C;E', 'Am;G', 'F;Em', 'F;F', 'G;G', 'Am;Am', 'Dm;Dm', 'C;A#', 'Em;F', 'C;G', 'G#;A#', 'F;Am', 'G#;Fm', 'Am;Gm', 'F;E', 'Dm;Am', 'Em;Em', 'G#;G#', 'Em;Am', 'C;Am', 'F;Dm', 'G#;G', 'F;A#', 'Am;G#', 'C;D', 'G;Am', 'Am;C', 'Am;A#', 'A#;G', 'Am;F', 'A#;Am', 'E;Am', 'Dm;E', 'A;G', 'Am;Dm', 'Em;Dm', 'C;F#m', 'Am;D', 'G#;Em', 'C;Dm', 'C;F', 'G;C', 'A#;A#', 'Am;Caug', 'Fm;G', 'A;A']  
Last 4 dimension corresponds to what part of song it is, as one of verse, pre-chorus, chorus, bridge (not sure about the order).

In data.json, you will see data like 64;1&3/4;1/8.
This represents one note of pitch 64 of length 1/8 placed at 1&3/4-th position within the two-bar window.
For each 59-dimension vector, you will have to convert the corresponding melody to this format using libraries like pretty-midi, etc.
